# Generated by Django 2.2.4 on 2020-03-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191105_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'BillingAddresses'},
        ),
    ]
